### ISSUE TITLE
[machine learning] Images directories structure is unclear.

### ISSUE THREAD

**Issue by cuckookernel** [KiwiCampusChallenge/Kiwi-Campus-Challenge#11]
Please specify whether when providing images in, for example, the `/user` directory, the file structure will be:
1.  flat (i.e. all files will be directly under `/user`) : 
```/user/00000.ppm
/user/00001.ppm
/user/00002.ppm
.
.
.
``` 
2. there will be subdirectories as in:
```/user/00/00000.ppm
/user/00/00001.ppm
/user/00/00002.ppm
...
/user/01/00000.ppm
/user/01/00001.ppm
/user/01/00002.ppm
``` 

Please also confirm that whatever structure we should follow will be the same as the one we should use in `train` and `test` directories

**Comment by KiwiCampusChallenge** [comment]
https://github.com/KiwiCampusChallenge/Kiwi-Campus-Challenge/issues/14
