### ISSUE TITLE
[machine learning] Python libraries allowed

### ISSUE THREAD

**Issue by davidmoncas** [KiwiCampusChallenge/Kiwi-Campus-Challenge#16]
I want to know which libraries are we allowed to use, specifically in image processing (openCv, Numpy, Scipy, PIL, Pillow, Scikit-image)

**Comment by KiwiCampusChallenge** [comment]
You can use all you want for image processing. However, as described, the machine learning models should only be written in TensorFlow and Scikit-learn.
