### ISSUE TITLE
[machine learning] validation phase directory structures

### ISSUE THREAD

**Issue by codejohnson** [KiwiCampusChallenge/Kiwi-Campus-Challenge#18]
Are you going during your final validation only to infer, or are you going to validate test/training too?

I´m asking, because for the training phases, I am using the name of the directories as a source of ClassID ('00','01','02',...). Then, I think it is important to be clear about the structure of your test directories when you use your own data, because you need to supply your own training classes, no matter if you use the same in the remote database we are using.

python app.py train -m [chosen model] -d [directory with trainig data]
python app.py test -m [chosen model] -d [directory with test data]

**Comment by KiwiCampusChallenge** [comment]
First, remember reading other questions first https://github.com/KiwiCampusChallenge/Kiwi-Campus-Challenge/issues/14

Moreover, the `download` command is responsible for setting the files for training and testing of your code.
