### ISSUE TITLE
[robotics] Task_2 Question+Turtlebot

### ISSUE THREAD

**Issue by JKWalleiee** [KiwiCampusChallenge/Kiwi-Campus-Challenge#21]
Hi
I have two questions about Task 2.

In the title of the activity says Turtlebot. We have to work with TurtleBot in stage or should work with the erratic robot defined in the cfg file?

I do not understand well what to do in task 2:
We must execute the corresponding commands and only record the bagfile? 
When you ask for the list of running nodes, should we upload a capture from the list of nodes? (bagfile does not save the name of the nodes). 
For the teleoperation of the robot, we must use our own nodes or can we rely on the existing nodes in ROS?

Thanks.

**Comment by KiwiCampusChallenge** [comment]
Hello,

For task 2, it consists of working with the environment defined in the cfg file. 
Once you have the map, the idea of task 2.2 is to control the robot by keyboard.

You can use packages and tools that ROS has defined previously, I mean, use packages or code well defined with the community. For example, SLAM code is not easy to build, if someone did it first, just use it! 

Also, if you want you could upload and screenshot to show node lists and packages lists.

Best,

JJ
