### ISSUE TITLE
[machine learning] Use of Python

### ISSUE THREAD

**Issue by Daniel-M** [KiwiCampusChallenge/Kiwi-Campus-Challenge#22]
Hi there, I see that most part of the challenge requires the use of several known Python libraries, (scikit-learn, for example). For the case of TensorFlow, I wonder if i can use the API for another language and make calls from the python script to it.

**Comment by KiwiCampusChallenge** [comment]
Please use Python only (together with Python libraries, or libraries with Python bindings).
