### ISSUE TITLE
[machine learning] LeNet Architecture

### ISSUE THREAD

**Issue by moralesarias94** [KiwiCampusChallenge/Kiwi-Campus-Challenge#23]
LeNet-5 architecture was initially designed for grayscale images or images with only 1 channel. Can we modify the first layer to be able to receive RGB images to the model?

**Comment by ManuelRios18** [comment]
I had a similar question!
When they say LeNet architcture, they mean that the numbers and size of the filters  have to be exactly as it is written on the paper?
Or we can change it and keep the classic **conv-activation-maxpooling**  architecture ?
