### ISSUE TITLE
[Global] Bitbucket

### ISSUE THREAD

**Issue by TheRedRascal** [KiwiCampusChallenge/Kiwi-Campus-Challenge#25]
Hey, hello.

I was wondering if we could use a Bitbucket repo instead of a Github repo?

Bitbucket will be a little bit more private than an open Github repo.

Thanks.

**Comment by KiwiCampusChallenge** [comment]
You could use BitBucket and GitLab while you develop your code. Nonetheless, you should migrate to GitHub when it its done. The reason is that we want the community to learn from each other.
