### ISSUE TITLE
[machine learning] What are we supposed to write in the reports?

### ISSUE THREAD

**Issue by egutierrezc93** [KiwiCampusChallenge/Kiwi-Campus-Challenge#27]
what do you mean with this sentence? "Also, you must write a report for each of the models, which will take the model saved from models/model1/saved/".

Maybe you want us to write a Jupyter notebook that load the model and print the accuracy.

**Comment by KiwiCampusChallenge** [comment]
You can write the report any way you want, showing anything you considered useful for a report. We do encourage you to do it in a Jupyter notebook (we think is the right tool for that).
