### ISSUE TITLE
[machine learning] Time limit today

### ISSUE THREAD

**Issue by CamiloInx** [KiwiCampusChallenge/Kiwi-Campus-Challenge#28]
Hi.

What is the time limit today to send the solution for the challenge?

Thanks.

**Comment by jcabrerahi** [comment]
Today, but check the mail

**Comment by ManuelRios18** [comment]
I guess 11:59

**Comment by JKWalleiee** [comment]
If I send the challenge today.... I have to share the public link to my repo?
