### ISSUE TITLE
[robotics] Task3_4 Question

### ISSUE THREAD

**Issue by JKWalleiee** [KiwiCampusChallenge/Kiwi-Campus-Challenge#29]
Hi.
In the bagfile recorded for the activity 3_4 should the mapping process be shown in gazebo and rviz simultaneously? or only in rviz?
or the idea is to record a bagfile with the map (already created) loaded and the robot navigating in it?
Thanks.

**Comment by KiwiCampusChallenge** [comment]
Hello,

Use the bag file to record rviz, gazebo and the map that you created.
Best,
JJ

**Comment by dacarva** [comment]
So the bag file should contain all the topics published by gazebo, rviz and the /map topic?
I am having this issue because if all these topics are recorded, the file size is huge (3.1 GB) and it can't be uploaded.
