### ISSUE TITLE
[machine learning] Using Keras

### ISSUE THREAD

**Issue by TheRedRascal** [KiwiCampusChallenge/Kiwi-Campus-Challenge#3]
Hello.

I was wondering if we can use keras with tensorflow, or just pure tensorflow?

Thanks.

**Comment by moralesarias94** [comment]
'It is very important that you implement and train the models in TensorFlow (tasks 4 and 5) from scratch. DO NOT use someone's else model. In fact, the description of the model of task 5 should reflect what the authors of the paper have proposed.'
