### ISSUE TITLE
[machine learning] Train and test data

### ISSUE THREAD

**Issue by moralesarias94** [KiwiCampusChallenge/Kiwi-Campus-Challenge#4]
In the webpage http://benchmark.ini.rub.de/?section=gtsdb&subsection=dataset they split the data into train(1.1gb) and test (˜500gb). The description of the challenge says that we should leave 80% for training and 20% for testing, so my question is: Do we have to split the full dataset (1.6gb) into 80-20 and store this in the corresponding folders or just download the train and test from the webpage in the folders and split the data into 80-20 for training-validation.

**Comment by srcolinas** [comment]
Please download the full data set (1.6GB) and do a random split your self.
