### ISSUE TITLE
[robotics] Ros Version

### ISSUE THREAD

**Issue by JKWalleiee** [KiwiCampusChallenge/Kiwi-Campus-Challenge#5]
Hi.
Do we have to work with ROS kinectic or can we work with INDIGO or HYDRO?
Thanks.

**Comment by KiwiCampusChallenge** [comment]
Hi, 
I prefer that you use Kinetic, however, if you want to use another version is ok, but I don't really sure if it is compatible with the tasks. Under your responsibility. 
Thank you
