### ISSUE TITLE
[machine learning] What do we have to predict?

### ISSUE THREAD

**Issue by moralesarias94** [KiwiCampusChallenge/Kiwi-Campus-Challenge#7]
It is not clear what the model has to predict. A type (mandatory...) or the kind of signal (snow, speed limit, etc). The input to the model is just the ROI? or the whole image?

**Comment by moralesarias94** [comment]
Also, the ground truth data has more than 900 rows, meaning that there are more than one ROI in each image. I want to know if I could create a sample per ROI?

**Comment by KiwiCampusChallenge** [comment]
https://github.com/KiwiCampusChallenge/Kiwi-Campus-Challenge/issues/6

Please search through the issues next time, that is the whole point.
