### ISSUE TITLE
[machine learning] Some questions about DL challenge

### ISSUE THREAD

**Issue by ManuelRios18** [KiwiCampusChallenge/Kiwi-Campus-Challenge#8]
Hello!

I just started working and I have a couple of questions

1.  The data set that we are using in this competition ( The German Traffic Sign **Detection** Benchmark ) has the Images stored in different folders according with its corresponding class (43 in total ) and  they are saved in PPM format. The first task says that we must create a piece of code able to download that data and store it into a folder called "Images" and split it into test and train folders, I am planning to save already them resized and with jpg format, there is any problem with that ? or should I store the images exactly as they are provided in the data set.

2. It is not specified how the labels of the images are provided. On the original data set the labels are  the folder name, but I understand that the folders "train" and "test" just contains the images so where should I store the labels of those images in order to train or test the system?
I was planning to do so by saving all the images with an specific format, for instance "class-index.jpg"
and in the reading process I would save that class "variable" on the image name.
But I not sure if doing this is right because I dont know how the judges are going to input the correct labels in the folder named "user" and they  try to test some model using that data !

3.  According with the issue [https://github.com/KiwiCampusChallenge/Kiwi-Campus-Challenge/issues/6](#6 ) we have to use the  data set that I refer in my first question, but I  notice that there are some unbalanced classes for instance class number 00 "speed limit 20 (prohibitory)" which has just 4 images!
What should we do in this case?, artificially increase the number of samples ?
If not this will imply some problems in task 3 and 4 since Logistic Regression is a binary classifier and we will have to use One-vs-Rest or any other similar technique.

**Comment by srcolinas** [comment]
Please open a separate question for each your have, that would make them easier to find for everyone.
